// <auto-generated />
using BlazorApp.Web.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlazorApp.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("BlazorApp.Web.Data.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companys");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "Adatech"
                        },
                        new
                        {
                            Id = 2,
                            CompanyName = "Ramwellcom"
                        },
                        new
                        {
                            Id = 3,
                            CompanyName = "Rosko"
                        },
                        new
                        {
                            Id = 4,
                            CompanyName = "RinoSoft"
                        },
                        new
                        {
                            Id = 5,
                            CompanyName = "Totor"
                        },
                        new
                        {
                            Id = 6,
                            CompanyName = "Engala"
                        });
                });

            modelBuilder.Entity("BlazorApp.Web.Data.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatronymicName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            FirstName = "Яков",
                            LastName = "Хохорин",
                            PatronymicName = "Андриянович",
                            PhoneNumber = "+79025873827"
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 3,
                            FirstName = "Светлана",
                            LastName = "Зарубина",
                            PatronymicName = "Захаровна",
                            PhoneNumber = "+79023675410"
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = 2,
                            FirstName = "Галина",
                            LastName = "Сутулина",
                            PatronymicName = "Владиленовна",
                            PhoneNumber = "+79024708102"
                        },
                        new
                        {
                            Id = 4,
                            CompanyId = 4,
                            FirstName = "Никита",
                            LastName = "Рощин",
                            PatronymicName = "Еремеевич",
                            PhoneNumber = "+79029648037"
                        },
                        new
                        {
                            Id = 5,
                            CompanyId = 3,
                            FirstName = "Авдей",
                            LastName = "Расторгуев",
                            PatronymicName = "Евгениевич",
                            PhoneNumber = "+79022480750"
                        },
                        new
                        {
                            Id = 6,
                            CompanyId = 5,
                            FirstName = "Онуфрий",
                            LastName = "Эрнет",
                            PatronymicName = "Леонович",
                            PhoneNumber = "+79022756964"
                        },
                        new
                        {
                            Id = 7,
                            CompanyId = 3,
                            FirstName = "Кир",
                            LastName = "Бысов",
                            PatronymicName = "Миронович",
                            PhoneNumber = "+79024425555"
                        },
                        new
                        {
                            Id = 8,
                            CompanyId = 2,
                            FirstName = "Евстигней",
                            LastName = "Александрин",
                            PatronymicName = "Андриянович",
                            PhoneNumber = "+79022032307"
                        },
                        new
                        {
                            Id = 9,
                            CompanyId = 6,
                            FirstName = "Кир",
                            LastName = "Жиленков",
                            PatronymicName = "Миронович",
                            PhoneNumber = "+79024661261"
                        },
                        new
                        {
                            Id = 10,
                            CompanyId = 1,
                            FirstName = "Людмила",
                            LastName = "Яцкевича",
                            PatronymicName = "Кузьмевна",
                            PhoneNumber = "+79024714458"
                        },
                        new
                        {
                            Id = 11,
                            CompanyId = 2,
                            FirstName = "Григорий",
                            LastName = "Петров",
                            PatronymicName = "Потапович",
                            PhoneNumber = "+79022839322"
                        },
                        new
                        {
                            Id = 12,
                            CompanyId = 5,
                            FirstName = "Инесса",
                            LastName = "Сайтахметова",
                            PatronymicName = "Тимофеевна",
                            PhoneNumber = "+79029903421"
                        });
                });

            modelBuilder.Entity("BlazorApp.Web.Data.Employee", b =>
                {
                    b.HasOne("BlazorApp.Web.Data.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });
#pragma warning restore 612, 618
        }
    }
}
